version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: saturday
    labels:
      - dependencies
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: '-'
    commit-message:
      prefix: fix(deps)
      prefix-development: chore(dev-deps)

  - package-ecosystem: npm
    directory: /backend/api
    schedule:
      interval: weekly
      day: saturday
    labels:
      - dependencies
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: '-'
    commit-message:
      prefix: fix(deps)
      prefix-development: chore(dev-deps)

  - package-ecosystem: gomod
    directory: /backend/auth
    schedule:
      interval: weekly
      day: saturday
    labels:
      - dependencies
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: '-'
    commit-message:
      prefix: fix(deps)
      prefix-development: chore(dev-deps)
