version: "3"

volumes:
  memoneo2_data:
    external: true
    name: memoneo2_data

networks:
  net:
    driver: bridge
  traefik:
    external:
      name: traefik_net

services:
  postgres_data:
    image: postgres
    volumes:
      - memoneo2_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATA_DB_NAME}
      POSTGRES_USER: ${DATA_DB_USER}
      POSTGRES_PASSWORD: ${DATA_DB_PASSWORD}
    networks:
      - net
    ports:
      - "5433:5432"

  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    container_name: auth
    depends_on:
      - postgres_data
    networks:
      - net
      - traefik
    labels:
      - docker-volume-backup.stop-during-backup=true
      - "traefik.enable=true"
      - "traefik.http.routers.memoauth.rule=Host(`auth.memoneo2.yourdomain.com`)"
      - "traefik.http.routers.memoauth.entrypoints=https"
      - "traefik.http.routers.memoauth.tls=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.memoauth.tls.certresolver=myresolver"
    environment:
      - ALLOW_ORIGINS=https://localhost:3000|http://localhost:8080|https://web.memoneo2.yourdomain.com
      - PORT=8089
      - DB_HOST=postgres_data
      - DB_PORT=5432
      - DB_STORE=${DATA_DB_NAME}
      - DB_USER=${DATA_DB_USER}
      - DB_PASSWORD=${DATA_DB_PASSWORD}
      - AUTH_COOKIE_DOMAIN=yourdomain.com
      - AUTH_JWT_KID=${AUTH_KID}
      - AUTH_JWT_SIGNING_KEY=${AUTH_JWT_SIGNING_KEY}
    ports:
      - "5002:8089"
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: api
    depends_on:
      - postgres_data
      - auth
    networks:
      - net
      - traefik
    labels:
      - docker-volume-backup.stop-during-backup=true
      - "traefik.enable=true"
      - "traefik.http.routers.memoapi.rule=Host(`api.memoneo2.yourdomain.com`)"
      - "traefik.http.routers.memoapi.entrypoints=https"
      - "traefik.http.routers.memoapi.tls=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.memoapi.tls.certresolver=myresolver"
    environment:
      - PORT=8073
      - AUTH_API_URL=http://auth:8089
      - DB_HOST=postgres_data
      - DB_PORT=5432
      - DB_STORE=${DATA_DB_NAME}
      - DB_USER=${DATA_DB_USER}
      - DB_PASSWORD=${DATA_DB_PASSWORD}
    ports:
      - "5013:8073"
    restart: unless-stopped
