/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNotes"];
        put?: never;
        post?: never;
        delete: operations["deleteNotes"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNotesIds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postNotesBulk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["putNote"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["putNotesById"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patchNotesByIdArchive"];
        trace?: never;
    };
    "/notes/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postNotesArchive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["putNotesByIdFile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
    getIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
    getNotes: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        user_id: string;
                        title: string;
                        body: string;
                        body_iv: string;
                        date: string;
                        archived: boolean;
                        version: number;
                        created_at: string;
                        updated_at: string;
                        file?: {
                            note_id?: string;
                            title: string;
                            path: string;
                        };
                    }[];
                };
            };
        };
    };
    deleteNotes: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    ids: string[];
                };
                "application/x-www-form-urlencoded": {
                    ids: string[];
                };
                "multipart/form-data": {
                    ids: string[];
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                    }[];
                };
            };
        };
    };
    getNotesIds: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        title: string;
                    }[];
                };
            };
        };
    };
    postNotesBulk: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    id: string;
                    /** Format: uuid */
                    user_id?: string;
                    title: string;
                    body: string;
                    body_iv: string;
                    date: string;
                    archived?: boolean;
                    version?: number;
                }[];
                "application/x-www-form-urlencoded": {
                    /** Format: uuid */
                    id: string;
                    /** Format: uuid */
                    user_id?: string;
                    title: string;
                    body: string;
                    body_iv: string;
                    date: string;
                    archived?: boolean;
                    version?: number;
                }[];
                "multipart/form-data": {
                    /** Format: uuid */
                    id: string;
                    /** Format: uuid */
                    user_id?: string;
                    title: string;
                    body: string;
                    body_iv: string;
                    date: string;
                    archived?: boolean;
                    version?: number;
                }[];
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        user_id: string;
                        title: string;
                        body: string;
                        body_iv: string;
                        date: string;
                        archived: boolean;
                        version: number;
                        created_at: string;
                        updated_at: string;
                        file?: {
                            note_id?: string;
                            title: string;
                            path: string;
                        };
                    }[];
                };
            };
        };
    };
    putNote: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    id: string;
                    /** Format: uuid */
                    user_id?: string;
                    title: string;
                    body: string;
                    body_iv: string;
                    date: string;
                    archived?: boolean;
                    version?: number;
                };
                "application/x-www-form-urlencoded": {
                    /** Format: uuid */
                    id: string;
                    /** Format: uuid */
                    user_id?: string;
                    title: string;
                    body: string;
                    body_iv: string;
                    date: string;
                    archived?: boolean;
                    version?: number;
                };
                "multipart/form-data": {
                    /** Format: uuid */
                    id: string;
                    /** Format: uuid */
                    user_id?: string;
                    title: string;
                    body: string;
                    body_iv: string;
                    date: string;
                    archived?: boolean;
                    version?: number;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        user_id: string;
                        title: string;
                        body: string;
                        body_iv: string;
                        date: string;
                        archived: boolean;
                        version: number;
                        created_at: string;
                        updated_at: string;
                        file?: {
                            note_id?: string;
                            title: string;
                            path: string;
                        };
                    };
                };
            };
        };
    };
    putNotesById: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    id?: string;
                    /** Format: uuid */
                    user_id?: string;
                    title?: string;
                    body?: string;
                    body_iv?: string;
                    date?: string;
                    archived?: boolean;
                    version?: number;
                };
                "application/x-www-form-urlencoded": {
                    /** Format: uuid */
                    id?: string;
                    /** Format: uuid */
                    user_id?: string;
                    title?: string;
                    body?: string;
                    body_iv?: string;
                    date?: string;
                    archived?: boolean;
                    version?: number;
                };
                "multipart/form-data": {
                    /** Format: uuid */
                    id?: string;
                    /** Format: uuid */
                    user_id?: string;
                    title?: string;
                    body?: string;
                    body_iv?: string;
                    date?: string;
                    archived?: boolean;
                    version?: number;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        user_id: string;
                        title: string;
                        body: string;
                        body_iv: string;
                        date: string;
                        archived: boolean;
                        version: number;
                        created_at: string;
                        updated_at: string;
                        file?: {
                            note_id?: string;
                            title: string;
                            path: string;
                        };
                    };
                };
            };
            /** @description Response for status 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    type: unknown;
                };
            };
        };
    };
    patchNotesByIdArchive: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    archived?: boolean;
                };
                "application/x-www-form-urlencoded": {
                    archived?: boolean;
                };
                "multipart/form-data": {
                    archived?: boolean;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        user_id: string;
                        title: string;
                        body: string;
                        body_iv: string;
                        date: string;
                        archived: boolean;
                        version: number;
                        created_at: string;
                        updated_at: string;
                        file?: {
                            note_id?: string;
                            title: string;
                            path: string;
                        };
                    };
                };
            };
            /** @description Response for status 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    type: unknown;
                };
            };
        };
    };
    postNotesArchive: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    ids: string[];
                };
                "application/x-www-form-urlencoded": {
                    ids: string[];
                };
                "multipart/form-data": {
                    ids: string[];
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                    }[];
                };
            };
        };
    };
    putNotesByIdFile: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title: string;
                    path: string;
                    /** Format: uuid */
                    note_id?: string;
                };
                "application/x-www-form-urlencoded": {
                    title: string;
                    path: string;
                    /** Format: uuid */
                    note_id?: string;
                };
                "multipart/form-data": {
                    title: string;
                    path: string;
                    /** Format: uuid */
                    note_id?: string;
                };
            };
        };
        responses: {
            /** @description Response for status 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        note_id?: string;
                        title: string;
                        path: string;
                    };
                };
            };
            /** @description Response for status 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    type: unknown;
                };
            };
        };
    };
}
